### ISSUE TITLE
Using HX-Redirect header working but causes JS errors

### ISSUE THREAD

**Issue by GitRon** [bigskysoftware/htmx#754] opened 2022-01-07 07:49 UTC
Hi there!

I just discovered the great "HX-Redirect" header! I need to click on a DOM element and make a redirect to a new page. It works like a charm but every time the redirect is executed, I get the following errors in my Firefox Developer Edition v96.0b:

![grafik](https://user-images.githubusercontent.com/3176075/148510111-55fae8a9-741e-4ac6-93f4-17c2423a6d03.png)

Am I missing something? Unfortunately, there is no code to show. I just send the header and everything apart from the error messages works. I am using htmx v1.4.1.

Thx in advance!  
Ronny

**Comment by 1cg** [comment] 2022-01-16 17:37
Are you invoking the request via javascript?

I think the problem is that we flag an abort, however it occurs, as an error in the console.  The good news is that it shouldn't affect functionality.

**Comment by GitRon** [comment] 2022-01-17 07:47
Hi @1cg 

you are right, everything works! And no, I just send the header and don't do any custom JS magic. Still, maybe this could be a warning or configurable? Might scare off some people?

Best  
Ronny

**Comment by 1cg** [comment] 2022-01-17 17:11
OK, I am going to close this issue, but will be thinking about how to deal with this.  I am working on adjacent functionality today so maybe something will spring to mind.

Thank you!
Carson

**Closed by 1cg** 2022-01-17 17:11 UTC
