### ISSUE TITLE
hx-push-url doesn’t work properly on device back button click

### ISSUE THREAD

**Issue by kawsaramin101** [bigskysoftware/htmx#854] opened 2022-03-07 08:42 UTC
I am trying to integrate Htmx with django and achieve single page application behaviour. I am rewritting Djangoproject.com poll app with htmx. When I click on detail page link, content loads, htmx push a new url in address bar. When I press back button, it took me to index page perfectly for the first time, after that if I again go to detail page and click back button, url shows of the index, but index content doesn’t load, content remains same as detail page. Here is my code -

```
views.py

def index(request):
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    if request.headers.get("Hx-Request") is not None:
        return render(request, 'main/index/index.html', context)
    else:
        return render(request, 'main/index/index-full.html', context)
    
    
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    print(request.headers.get("Hx-Request"))
    if request.headers.get("Hx-Request") is not None:
        return render(request, 'main/detail/detail.html', {'question': question})
    else:
        return render(request, 'main/detail/detail-full.html', {'question': question})
    
```

```
index.html

<div id="index" class="">

    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><div class="has-text-link" hx-get="{% url 'main:detail' question.id %}" hx-push-url="true" hx-target="#index" hx-swap="outerHTML">{{ question.question_text }}</div></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>
        No polls are available.
    </p>
    {% endif %}

</div>

index-full.html

{% extends 'base.html' %}
{% block content %}
{% include 'main/index/index.html' %}
{% endblock content %}
```

```
detail.html

<div id="detail" class="">

    <form action="{% url 'main:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p>
                <strong>{{ error_message }}</strong>
            </p>
            {% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>

</div>


detail-full.html

{% extends 'base.html' %}
{% block content %}
{% include 'main/detail/detail.html %}
{% endblock content %}

```

I found no error in browser console, no error in terminal

Now, I know I can put a back button in detail page that can took me to index page. But user won't use that, they will just use the back button on their device. 
Note- I am on Android and talking about the back button in mobile phones

**Comment by josephetareh** [comment] 2022-03-14 11:01
also experiencing a pretty similar issue, were you able to get a workaround for this @kawsaramin101?

**Comment by kawsaramin101** [comment] 2022-03-14 21:19
@josephetareh Nope :(   
I had to ditch the idea of single page like behaviour. 
But, you can put this js in your code, so it will reload the page if user clicks back or forward button of the browser (not of the device).
```
var auxBack = performance.getEntriesByType("navigation");

if (auxBack[0].type === "back_forward") {
    location.reload(true);
}
```

**Comment by David-Guillot** [comment] 2022-04-13 16:07
I've been tracking down this issue with some dirty `console.log()`. It appears that on second occurrence of Back button click, the content of the `hx-history-elt` (or `<body>`) is saved on history cache under the wrong URL. It's clearly related to the `currentPathForHistory` variable which is somehow updated between getting to the detail page for the second time and hitting Back button for the second time.

@1cg any idea on this? This issue seriously hurts usability of interfaces using htmx...

**Comment by 1cg** [comment] 2022-04-15 15:37
Can I get a list of navigations that is causing this issue in the following format:

* click `<button hx-get="/foo" hx-push-url=true`
* click `<button hx-get="/bar" hx-push-url=true`
* click back button
* click back button <-- history is incorrect

I am trying to reproduce locally and I am unsuccessful so far.

**Comment by 1cg** [comment] 2022-04-15 15:51
Trying to reproduce and not able to :point_up: if someone can help me get this manual test written I will try to fix.

**Comment by David-Guillot** [comment] 2022-04-15 16:21
We have a steps-to-reproduce on our production website, if you're not afraid of French contents:
1. Go to https://www.contexte.com/chercher ; it's a faceted search interface for editorial contents about French politics, and it is very successfully leveraging htmx
2. Open a facet (for example a Hub) and select a value ; it will load results on the main section and update facets
3. Open another facet and select another value to refine your search ; new results will load
4. Hit the Back button ; htmx will successfully load the previous state (your single-facet search)
5. Again, open the same second facet and select the same value
6. Again, hit the Back button ; this time the single-facet URL will appear in the URL bar, but the previous state will not be displayed (your 2-facets search will remain displayed)

I was not able to write a manual test about it, which makes me think the issue is fairly complex. I have been able to notice the weird overriding of `currentPathForHistory` but not isolate the cause.

**Comment by josephetareh** [comment] 2022-04-15 16:38
When I was facing this issue, I would say it was more along the lines of:

1. click `<button hx-post="/foo" hx-push-url=true`
2. go back
3. click `<button hx-post="/foo" hx-push-url=true`
4. go back <-- history is incorrect

Here, I do believe that `foo` was really any other link on the page, and not just specifically the same one. 

Essentially, if I visit a link then go back,  then visit attempt to visit the link again and try to go back it fails. It really was quite a specific and funny issue, though I was able to side step it by setting the historyCacheSize to 0. 

I am still in development so I made the change just now and was able to reproduce it.

**Comment by 1cg** [comment] 2022-04-15 16:43
@josephetareh are you on 1.7.0?

**Comment by josephetareh** [comment] 2022-04-15 16:44
@1cg Yes.

**Comment by josephetareh** [comment] 2022-04-15 16:45
If you cannot reproduce it, I am beginning to wonder if django is breaking this somehow as @kawsaramin101 was using django and so am I. @David-Guillot are you also developing in django by any chance?

**Comment by David-Guillot** [comment] 2022-04-15 16:47
Yes we're using django with django-htmx

**Comment by 1cg** [comment] 2022-04-15 17:02
I think most htmx users are on django, so I don't blame django here :)

here is some debugging code that might help see what is going on:

https://gist.github.com/1cg/6f1d75674b12e780104407e8f5601060

We can refine it (and maybe add more events to htmx) to see what is going on.  Can you guys run your code w/ this and report back the results?

**Comment by josephetareh** [comment] 2022-04-15 17:48
These are the results from my console here. Also used some `console.log()` statements here to hopefully help you make sense of it. 

<img width="959" alt="Screenshot 2022-04-15 at 18 37 19" src="https://user-images.githubusercontent.com/36375714/163603095-cf9a3848-e8b3-4ec0-93c4-9d0ba9d76842.png">

[Do note that in the line where I say "after clicking back button: currently back at .../manage-products going back to .../order-history" I mean I am revisiting the order-history link and not actually using the back button in this instance. Hopefully this helps

**Comment by benboughton1** [comment] 2022-04-15 21:58
I see this bug with bottle.py so not exclusive to django. I will attempt a
minimal code that replicates the bug over next 24hrs.

**Comment by benboughton1** [comment] 2022-04-16 11:21
```
import bottle

app = bottle.app()


@bottle.route('/static/<filepath:path>')
def server_static(filepath):
    return bottle.static_file(filepath, root='static')


@bottle.route('/')
def home():
    return bottle.template('''
    <html>
        <body>
            <b>click test, go back, click test again and notice you can't come back!</b>
            <div id="work_area">
                <div hx-target="#work_area">
                    <button 
                    hx-get="/test/partial"
                    hx-push-url="/app/test">test</button>
                </div>
            </div>
        <script src="https://unpkg.com/htmx.org@1.7.0"></script>
        </body>
    </html>
    ''')

# partial
@bottle.route('/test/partial')
def test_page():
    return bottle.template('''
    <div>
    go back! this will be stuck here on the second go. 
    </div>
    ''')

bottle.run()

```

**Comment by 1cg** [comment] 2022-04-16 12:07
absolute :crown:

**Comment by gone** [comment] 2022-04-16 20:13
Just did a debug of this, and in the bottle example the error is coming from reloading htmx multiple times. It looks like on the reload of the cached version the currentPathForHistory is reset when it loads. 

You can fix the bottle example by EITHER setting currentPathForHistory in the htmx source to window.currentPathForHistory (making it a global) or by moving the htmx load to the head like so:

 ```
   return bottle.template('''
    <html>
    <head>
        <script src="/static/htmx.js"></script>
    </head>
        <body>
            <b>click test, go back, click test again and notice you can't come back!</b>
            <div id="work_area">
                <div hx-target="#work_area">
                    <button
                    hx-get="/test/partial"
                    hx-push-url="/app/test">test</button>
                </div>
            </div>
        </body>
    </html>
    ''')
```

Another example of multiple initialization is the loading styling being applied multiple times. @David-Guillot I'm pretty sure this is the same case for the bug you're seeing because after clicking through a couple of your hubs I can see in the header multiple instances of: 

`<style>                      .htmx-indicator{opacity:0;transition: opacity 200ms ease-in;}                      .htmx-request .htmx-indicator{opacity:1}                      .htmx-request.htmx-indicator{opacity:1}                    </style>
`

which makes me think you are also reloading htmx multiple times.

I think the workaround right now is moving htmx to your header - @1cg should the long term fix be having htmx notice it's already been loaded and do nothing?

**Comment by benboughton1** [comment] 2022-04-17 11:29
@gone Good one! Thanks for figuring that out. I think I may have had the same issue with bootstrap adding additional event handlers to dropdowns stopping them from working when going back.

**Comment by David-Guillot** [comment] 2022-04-17 12:48
Wow @gone nice catch!! Just tested importing of `htmx.js` from `<head>` instead of `<body>`, the issue is... gone :wink: . Let's see what the best fix is :+1:

**Comment by 1cg** [comment] 2022-05-13 01:48
I have merged @gone 's change so this issue should not come up in the future.

Very sorry folks!

**Closed by 1cg** 2022-05-13 01:48 UTC

**Comment by oersted** [comment] 2022-08-21 19:08
I'm experiencing similar symptoms on 1.8.0 (at least on Safari)

- In URL `/bar`
- click `<div hx-get="/foo" hx-push-url=true hx-target="main"`
- click back button -> the URL is `/bar` (correct) but the content is the same as for `/foo` (incorrect)

I'm also getting the following error in the console: `SyntaxError: The string did not match the expected pattern.` being thrown from `querySelector` at `htmx-1.8.0.min.js:608`.

(let me know if it would be more appropriate to post this as a separate issue)

**Comment by croxton** [comment] 2022-10-11 09:58
I'm seeing an issue with the back button behaviour in Safari on the latest version iOS using htmx 1.8.0 - but NOT the Chrome or Firefox apps on iOS (which also use Webkit, so that is surprising) or Android. What I observe is that, intermittently, some pages in the visited history are skipped entirely in the history sequence.

I was already setting the header `Vary: HX-Request` so cache compositing shouldn't be a problem.

What seemed to resolve the issue was move htmx to the `<head>`, which *I think* suggests that either double instantiation of htmx is the problem, or there was a race condition somewhere with my own code.

**Comment by Nigel2392** [comment] 2023-09-09 21:48
I found the following on reddit:
[Cache-Control](https://www.reddit.com/r/django/comments/15fah4j/htmx_hxpushurl_not_working_with_forward_and_back/)

Someone fixed it by setting HTMX requests to no-cache:
Fixed this issue using cache control header.

`if "HX-Request" in self.request.headers: response["Cache-Control"] = "no-store, max-age=0" return response`

(Thought I prefer using: `"no-cache, no-store, must-revalidate"`)
