### ISSUE TITLE
Problem with inserting a new row in a table with hx-swap-oob

### ISSUE THREAD

**Issue by applecat** [bigskysoftware/htmx#627] opened 2021-10-20 14:47 UTC
I'm trying to reproduce an example from [Docs - Updating Other Content - Solution 2: Out of Band Responses](https://htmx.org/examples/update-other-content/#oob).

It works great with `div`'s, but I faced problem with inserting a new row in table.
The problem is that a new row inserts without surrounding `<tr>` tag.

<img width="270" alt="Снимок экрана 2021-10-20 в 17 42 23" src="https://user-images.githubusercontent.com/390483/138115420-70df55f3-50dd-439a-8d91-88af481533a5.png">

<img width="711" alt="Снимок экрана 2021-10-20 в 17 42 44" src="https://user-images.githubusercontent.com/390483/138115469-1c5c2c8a-be9e-48f5-8fb5-fab95c657bfd.png">

Here is the code:
```index.html
<h2>Contacts</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="contacts-table">      
  </tbody>
</table>
<h2>Add A Contact</h2>
<form hx-post="/contacts">
  <label>
    Name
        <input name="name" type="text">  
  </label>
  <label>
    Email
        <input name="email" type="email">  
  </label>
  <button type="submit">submit</button>
</form>

<script src="https://unpkg.com/htmx.org@1.6.0/dist/htmx.js"></script>
<script type="text/javascript">htmx.config.useTemplateFragments = true;</script>
```

Response from POST request to `/contacts`:
```
<tr hx-swap-oob="beforeend:#contacts-table">
    <td>Joe Smith</td>
    <td>joe@smith.com</td>
</tr>
<form hx-post="/contacts">
  <label>
    Name1
        <input name="name" type="text">  
  </label>
  <label>
    Email
        <input name="email" type="email">  
  </label>
  <button type="submit">submit</button>
</form>
```

**Comment by makeworld-the-better-one** [comment] 2021-10-21 02:41
Just came here to report a similar issue, I expect it's caused by the same thing? Sending oob data with a `tbody` top-level tag fails to insert anything into the DOM, but using `table` works fine.

Setting `useTemplateFragments` makes it work fine though, thanks for the tip.

**Comment by 1cg** [comment] 2021-11-02 22:23
closing since it looks like we have a solution

i hate table parsing

**Closed by 1cg** 2021-11-02 22:23 UTC

**Comment by ediril** [comment] 2022-03-07 06:30
I ran into this problem too. You should consider fixing the example [here](https://htmx.org/examples/update-other-content/). It doesn't work as is. In the response, when I wrap the <tr> with <tbody>, then it works and doesn't seem to require setting `htmx.config.useTemplateFragments` to `true`.
