### ISSUE TITLE
Expression Evaluation in trigger filters

### ISSUE THREAD

**Issue by benpate** [bigskysoftware/htmx#264] opened 2020-12-13 03:23 UTC
I'm using the most recent DEV branch, and trying to make a trigger that only fires when the primary mouse button is clicked.  My first pass is to try `hx-trigger="mouse down[button==0]"` but this does not seem to work.  However, this works: `hx-trigger="mouse down[!button]"` which makes me think that the `==` is an invalid operation.  Is that true?

Are there rules to this that we can document better?  Or, is this something that *should* work, but is not.

**Comment by Dresdn** [comment] 2020-12-31 22:19
I'll piggyback on this as I'm trying to trigger off a specific `htmx.afterRequest` event, but I can't figure out how. My initial thoughts were similar to @benpate by doing `hx-trigger="htmx.afterRequest[target] == 'blah'"`, but any variations of using `==` throws an error.

**Comment by 1cg** [comment] 2020-12-31 23:30
hmm, maybe I don't parse that correctly.  I'll add a test for it.

**Comment by 1cg** [comment] 2021-01-02 03:12
OK, I added a test to ensure that `==` works, and it passes:

https://github.com/bigskysoftware/htmx/commit/afa6658648abccc885372acf821e7668133d93b4

@benpate I might need to create a manual test to see if the button filter is working correctly

**Comment by Dresdn** [comment] 2021-01-02 03:46
Thanks @1cg - this might be a little off topic then, but I can't get `hx-trigger` to trigger on the `htmx:*` events. Here's an example I put together:

```
<button hx-get="/first" hx-target="#first">Click</button>
<div id="first"></div>
<div id="second" hx-get="/second" hx-trigger="htmx:afterRequest[detail.target.id=='first']"></div>
```

When looking at the logs, I see the events from clicking **#first**, but then **#second** never triggers.

Since the expression within the brackets needs to evaluate to `true`, I even tested with `hx-trigger="htmx:afterRequest[true]` to no avail. Is my example above correct?

**Comment by 1cg** [comment] 2021-01-02 03:54
@Dresdn I think for what you want, you need something I just implemented in dev, the `from` modifier for triggers:

```html
<button id="btn" hx-get="/first" hx-target="#first">Click</button>
<div id="first"></div>
<div id="second" hx-get="/second" hx-trigger="htmx:afterRequest from:#btn]"></div>
```

Not 100% sure this will work, but it should.  Note that I'm listening to the button, not the target div, since the `htmx:afterRequest` event is fired on the requesting element, not the target.

**Comment by 1cg** [comment] 2021-01-03 18:40
OK, I now have enough tests that I'm pretty certain that the `==` operator works properly.  I'm going to close this out unless reproduced post-1.1.0

**Closed by 1cg** 2021-01-03 18:40 UTC
