### ISSUE TITLE
`HX-Trigger` breaks when the event name contains `.` characters

### ISSUE THREAD

**Issue by zilti** [bigskysoftware/htmx#427] opened 2021-03-19 16:09 UTC
Okay, pressing "return" in the title apparently makes GIthub create an empty issue... Sorry for that.

So. We are in the process of converting our last couple Intercooler pieces to HTMX and had an event `interview.request.successful`. That worked fine with Intercooler, but once converted for HTMX, it fails due to the periods. The way to make it work was to change the event name to `interviewRequestSuccessful`.

**Comment by 1cg** [comment] 2021-03-21 01:59
Huh.  I added a regression test for dot separated event names, and it worked fine:

https://github.com/bigskysoftware/htmx/issues/427

I wonder if the problem is that you were relying on jquery namespacing?

**Comment by zilti** [comment] 2021-03-22 08:41
Wouldn't that not be a problem when not using jquery anymore? The whole thing was 

```javascript
document.body.addEventListener('interview.request.successful', () => {
  // Code here
});
```

and on the server side `HX-Trigger: interview.request.successful`. Not sure why that would/did break and this new regression test wouldn't, but I wanted to add it for completeness' sake.

**Comment by 1cg** [comment] 2021-03-25 18:24
Are you by any chance using an `outerHTML` swap?  I wonder if it's something around that. (although I don't know why removing the dots would make a difference.)

Sorry, this one has me stumped.  Dots shouldn't do anything!

**Comment by zilti** [comment] 2021-03-31 16:07
No, nothing with `outerHTML` or even anything HTMX-specific apart from using `HX-Trigger` to trigger the event. All the event does is trigger a JavaScript function.

**Comment by 1cg** [comment] 2021-07-07 15:18
I am going to close this out pending a regression test that can replicate it.  My regression test works fine.

**Closed by 1cg** 2021-07-07 15:18 UTC
