### ISSUE TITLE
hx-on:* event handlers broken inside shadow DOM (v2.0.0.beta1)?

### ISSUE THREAD

**Issue by jaarasys-henria** [bigskysoftware/htmx#2406] opened 2024-03-17 20:29 UTC
I'm currently hacking around with custom HTML elements and shadow DOM. I was testing out v2.0.0.beta1's enhanced shadow DOM compatibility.

I think there might be a bug with hx-on:* event handlers inside custom elements. Something's causing them to not fire.

I don't think there was a test for shadow DOM and event handlers, only the core behavior. I tried copying the basic event test from test/attributes/hx-on-wildcard.js into test/core/shadowdom.js. The test failed.

Given that it's entirely possible that I screwed that up at this hour, I tried creating a basic code, which also seems to repro this behavior.

Genuine bug or did I just overlook something?

I thought this might be related to shadow DOM nodes not letting their events bubble out of the shadow DOM tree, but that can't be it, can it?

I can take a bit harder look at some other time. Clock says it's sleepy time now.

```html
<!DOCTYPE html>

<template id="htmxeventdestroyer-template">
    <button hx-on:click='console.log("shadow dom foo 2")'>Shadow DOM Button 2</button>
</template>

<html>

<head>
    <title> HTMX hx-on:* bug repro </title>
    <script src="htmx.min.2.0.0.beta1.js"></script>
    <script>
        htmx.logAll()
        class HTMXEventDestroyer extends HTMLElement {
            constructor() {
                super()
                this.attachShadow({mode: "open"})

                // Add content with non-template tag and template tag methods
                this.shadowRoot.innerHTML = `<button hx-on:click='console.log("shadow dom foo 1")'>Shadow DOM Button 1</button><br><br>`

                const template = document.querySelector("#htmxeventdestroyer-template")
                const content = template.content.cloneNode(true)
                this.shadowRoot.appendChild(content)

            }

            connectedCallback() {
                console.log("Custom element joined the party")
                htmx.process(this.shadowRoot)
                console.log("Shadow root processed by HTMX")
            }
        }

        customElements.define("htmx-event-destroyer", HTMXEventDestroyer)
    </script
</head>

<body>
    <button hx-on:click='console.log("light dom foo")'>Light DOM Button</button><br><br>
    <htmx-event-destroyer></htmx-event-destroyer>
</body>

</html>
```

**Comment by jaarasys-henria** [comment] 2024-03-18 17:40
Hmm... 7e484f65, which is included in v2.0.beta1, specifically mentions fixing event listeners.

However, `findHxOnWildcardElements()` includes a condition which explicitly skips handling anything inside ShadowRoot. This condition was introduced by original shadow DOM support implementation in #2075.

There's a seemingly closely related comment about global event handlers from 4d9adabe6 inside `makeEvent()`'s body.

This is all the heads and tails I can make off of this with some quick exploration.

Finally a reason to take a quick dive into HTMX source :D

**Comment by kgscialdone** [comment] 2024-03-23 16:38
This is a regression caused by changes to [findHxOnWildcardElements](https://github.com/bigskysoftware/htmx/blob/dev/src/htmx.js#L2605), which removed the fallback method that manually scans for attributes instead of using XPATH. Since XPATH doesn't work directly on shadow roots, it needs to either be applied to each child element of the shadow root individually, or apply a fallback approach - in this case, the condition that previously caused shadow roots to fall back on the same approach used when XPATH is not supported now simply prevents checking for `hx-on:*` in shadow DOM at all, as XPATH support is now assumed.

**Comment by 1cg** [comment] 2024-05-15 17:58
Should be fixed with https://github.com/bigskysoftware/htmx/commit/01cb5e0d8dd497c0a5f24afb7d00753e84b408e4

**Closed by 1cg** 2024-05-15 17:58 UTC
Labels: 2.0
