### ISSUE TITLE
Install via npm and `import`?

### ISSUE THREAD

**Issue by johndwells** [bigskysoftware/htmx#34] opened 2020-05-23 13:11 UTC
I've just tried to import htmx into our build (webpack), and while it builds fine, in the browser I get the following JS error:

`Uncaught TypeError: Cannot read property 'logger' of undefined`

It's entirely possible that the JS is being mangled by webpack, perhaps the minification routine, but I'm not importing it any differently than any other package (flickity, alpine, etc).

Any tips would be appreciated!

**Comment by chg20** [comment] 2020-05-23 15:47
Hi john,

This is almost certainly due to the way I define htmx.  I'm using my old-school functional-style mechanism.  Unfortunately I don't have any experience with webpack, but if you can figure out what the issue is I'm happy to change up the way I declare htmx to be compatible with it.

Maybe I need to switch to UMD? https://github.com/umdjs/umd

**Comment by johndwells** [comment] 2020-05-23 16:01
I wish I knew more about how this would need to be built to work in this scenario. I think it needs to be "exported" somehow, but my JS skills are quite limited... I'll see if I can recruit some help.

**Comment by nateberkopec** [comment] 2020-05-24 00:59
I think you'll have to define HTMX as an ES6, AMD or CommonJS module to work with Webpack w/o a shim.

**Comment by nateberkopec** [comment] 2020-05-24 01:23
You can use the raw-loader:

```
import('raw-loader!htmx.org/dist/htmx').then(rawModule => eval.call(null, rawModule.default))
```

That does fail for me anyway because htmx internally refers to itself, but `htmx` is not yet defined so Webpack blows up. Defining htmx and then redefining it works:

```
var htmx = {};
var htmx = (function () {
```

**Comment by chg20** [comment] 2020-05-25 05:02
OK, I tried my best, the AMD stuff is bonkers:

**Comment by johndwells** [comment] 2020-05-25 13:37
I've looked at AlpineJS, and it appears to use Rollup to handle all of the module building:

https://rollupjs.org/

So perhaps after a bit of restructuring, it wouldn't be so bad moving forward.

**Comment by chg20** [comment] 2020-05-26 20:28
The 0.0.4 release includes an attempt by me to make it work w/ AMD.  Let me know if this helps.

**Comment by chg20** [comment] 2020-05-27 17:31
@johndwells can you verify if this now works?

**Comment by johndwells** [comment] 2020-05-27 18:40
@chg20 I got it to work using @nateberkopec's suggestion to redefine it first, e.g. this now works with 0.0.4:

```
window.htmx = {};
window.htmx = require('htmx.org');
```

But I wouldn't say that's _properly_ implemented - but it's enough to keep me going for now, so thanks! :)

**Comment by chg20** [comment] 2020-05-29 21:27
yeah, that's pretty terrible.

any pointers on how not to refer to htmx within htmx itself @nateberkopec ?

**Comment by nateberkopec** [comment] 2020-05-29 23:09
oh no, someone has mistaken me for a javascript guy! I just write Ruby, I swear! 😆 

sorry @chg20, we've already exhausted my personal knowledge of JS packaging 🤣

**Comment by GavinRay97** [comment] 2020-05-30 20:56
@chg20 I have a fair bit of experience with different bundlers and could take a crack at this when I've got the time if you'd like?

**Comment by GavinRay97** [comment] 2020-05-30 22:11
Okay, I got it working.

So what I did was:

1. Took all of the IIFE stuff that was defined in some of the extensions (wrapping them in `(function () { })()`) out first

2. Removed the AMD stuff from the main `htmx.js` and put it back to the way it was initially written:

```js
var htmx = htmx || (function () {
        'use strict';
```

So now in the top of the bundle there's an IIFE that defines `htmx`.

This library is written in a bit of an usual style, without using imports/exports. So there's a sort of "stateful" dependence with these modules.

The easiest way to get around this is to deterministically load the contents of the entrypoint/main bundle first, so that in the order of execution the `var htmx =` IIFE is always loaded before any other code from extensions etc. can reference it.

I used a small gulpfile to concatenate the contents of `htmx.js` and all of the extension code into a single bundle:

```js
// gulpfile.js
const { src, dest } = require('gulp')
const concat = require('gulp-concat')

// This always reaches `htmx.js` first since it's in a closer directory
// But probably better to explicitly pipe `htmx.js` and then all others
exports.default = function () {
  return src('src/**/*.js')
	.pipe(concat('htmx-bundle.js'))
	.pipe(dest('output/'))
}
```

This spits out a single-file bundle that works perfectly in browser containing all extension code. (This may or may not be desirable, I just wanted to test extension functionality too so this was easiest).

Then the last bit is to expose it as an export. You can do this manually by tacking on `module.exports = htmx` at the bottom of `htmx-bundle.js`, but Rollup has a plugin for this called `plugin-legacy` made for older-style modules that don't use imports/exports.

https://github.com/rollup/rollup-plugin-legacy

It's overkill to use it just for this, but you could use it to pro grammatically apply exports to all the extensions so that they could be packed and imported separately from the main program if you like.

```js
// rollup.config.js
import legacy from '@rollup/plugin-legacy'

export default {
  input: ['htmx-bundle.js'],
  output: {
    format: 'cjs',
    file: 'htmx-cjs.js',
  },
  plugins: [legacy({ 'htmx-bundle.js': 'htmx' })],
}
```

Then to test it, I made a single JS file where I attempted to import the generated `htmx-cjs.js`, included it into an `index.html`, and ran `parcel index.html` to bundle it:

```html
<html>
  <body>
    <h1>Test</h1>
  </body>
  <script src="test.js"></script>
</html>
```
```js
import htmx from './htmx-cjs'
console.log('got htmx', htmx)

const h1 = htmx.closest(document.querySelector('h1'), 'body')
console.log('closest h1', h1)
```

![image](https://user-images.githubusercontent.com/26604994/83339883-ff99f100-a29f-11ea-999c-db7292b16a43.png)

![htmx-module](https://user-images.githubusercontent.com/26604994/83339933-9f577f00-a2a0-11ea-8fc5-47dde1fd2f58.gif)

**Comment by GavinRay97** [comment] 2020-05-30 22:12
(For the record it would be a lot easier to do this if regular imports/exports were used in the library code and the generated bundle for the browser was done with a small build script like a standard library)

**Comment by chg20** [comment] 2020-05-30 22:23
it's almost like i hate javascript and I'm writing all this javascript to avoid writing javascript

**Comment by GavinRay97** [comment] 2020-05-30 23:14
> it's almost like i hate javascript and I'm writing all this javascript to avoid writing javascript

I couldn't tell from the commit messages :joy:
![image](https://user-images.githubusercontent.com/26604994/83340577-03317600-a2a8-11ea-84a5-3f24c6669e54.png)

I've written JS for a while. Like, before-SPA's-and-ES6/HTML5-were-a-thing while.

I feel like a lot of the pain in JS comes from two things:

- The language is incredibly malleable. It's multi-paradigm and doesn't really have a preference on how you write your code. This lack of structure can be useful or horrible.

- Quirky behavior and dynamic types. This is why I write Typescript now.

Or you can just hate the language for any arbitrary reason. That's perfectly human too.

**Comment by shanecp** [comment] 2020-06-06 07:50
Having the same issue. Couldn't load directly on the browser (as described on the installation instructions). Had to get the unminified `htmx.js` and change AMD loading lines:

```
window.htmx = htmx || (function () {
        'use strict';
...
```

**Comment by bencroker** [comment] 2020-09-02 19:35
Possibly fixed by https://github.com/bigskysoftware/htmx/pull/172.

**Comment by dkniffin** [comment] 2020-09-03 11:52
I haven't tested it yet, but assuming #172 fixed this, I would expect three more things before this can be closed out:
1. The docs should be updated to show how to install via npm and use via ES6 `import`. This will make the library a lot more approachable for anyone already using that type of system
2. Tests. The importing of the library is a very core requirement, and I definitely don't want to see that break from a future change. Tests will ensure that
3. A new release, so we can start using it

**Comment by qqilihq** [comment] 2020-09-13 09:30
Thanks for the valuable information to everyone.

Had this issue when loading via Webpack:

```
htmx.min.js:1865 Uncaught ReferenceError: htmx is not defined
    at pt (htmx.min.js:1865)
    at HTMLDocument.eval (htmx.min.js:1890)
```

I just gave @bencroker’s #172 from the `dev` branch a try:

```
yarn add git+https://github.com/bigskysoftware/htmx.git#a63d272441506d2d443725d0f855345078f2e98a
```

nb: Import in my Webpack entry file like so for nw (change is not yet reflected in the `dist/`):

```
import 'htmx.org/src/htmx.js';
```

And the issue seems to be solved! Thanks!

**Comment by 1cg** [comment] 2021-07-06 21:31
closing out as fixed

**Closed by 1cg** 2021-07-06 21:31 UTC
Labels: help wanted
