### ISSUE TITLE
Cache GET requests

### ISSUE THREAD

**Issue by hanifbirgani** [bigskysoftware/htmx#1989] opened 2023-11-10 16:48 UTC
I would like to understand how to leverage the browser's JavaScript cache to store responses from GET requests made by htmx in order to minimize redundant requests and repeated content delivery. This approach not only optimizes performance but also reduces the load on the server. Let me illustrate this with a commonly used example:

Consider a scenario with two dropdown menus on my webpage: the first one contains a list of states, and the second one dynamically populates with cities based on the selected state. When a user chooses state-1, htmx sends a GET request to the server, retrieves the list of cities for state-1, and populates the second dropdown accordingly. If the user then selects state-2, htmx similarly fetches the list of cities for state-2.

Up to this point, htmx has made two GET requests, which is acceptable. However, if the user re-selects state-1, htmx initiates another new request to the server. This last request is redundant and could be cached to avoid unnecessary server load. How can I efficiently store these responses in a JavaScript object to prevent such duplicated requests and responses?

I have developed an extension to implement this functionality. While the extension effectively caches the responses, it currently lacks additional processes after receiving a standard response. In other words, it does not swap the content of the target element, for example.

Here is the extension:
```javascript
(function () {
  var cacheStorage = {}; // Storage object for caching

  // Remove trailing slash from a url
  function removeLastUrlSlash(url) {
    return url.slice(0, url.lastIndexOf("/"));
  }
  // Helper method for caching response
  function cacheResponse(url, response) {
    cacheStorage[url] = response; // Save response in cache
  }

  // Helper method for checking if cache exists for a URL
  function getCachedResponse(url) {
    return cacheStorage[url]; // Retrieve response from cache
  }

  // Define the htmx cache extension
  htmx.defineExtension("cache", {
    onEvent: function (name, evt) {
      console.log(evt);
      var elt = evt.detail.elt;
      var target = evt.detail.target;

      // Intercept the request before it's sent
      if (
        name === "htmx:beforeRequest" &&
        elt.hasAttribute("hx-get") &&
        elt.getAttribute("hx-cache") === "memory"
      ) {
        console.log(cacheStorage);
        var url =
          removeLastUrlSlash(
            evt.detail.requestConfig.headers["HX-Current-URL"]
          ) + evt.detail.pathInfo.finalRequestPath;

        // If the response is cached, prevent the default request
        var cachedResponse = getCachedResponse(url);
        if (cachedResponse) {
          evt.preventDefault(); // Prevent the htmx request
          // handleAjaxResponse(target, cachedResponse); // Handle the cached response
          return false; // Stop further processing
        }
      }

      // Intercept the response before it's processed
      if (
        name === "htmx:afterOnLoad" &&
        elt.hasAttribute("hx-get") &&
        elt.getAttribute("hx-cache") === "memory"
      ) {
        var url =
          removeLastUrlSlash(
            evt.detail.requestConfig.headers["HX-Current-URL"]
          ) + evt.detail.pathInfo.finalRequestPath;
        cacheResponse(url, evt.detail); // Cache the response
      }

      return true; // Continue processing other events
    },
  });
})();
```

**Comment by Telroshan** [comment] 2023-11-10 17:41
Maybe a naive question, but why don't you take advantage of the [Cache-Control header](https://developer.mozilla.org/docs/Web/HTTP/Headers/Cache-Control) there?
If you sent it from your server, the browser would handle caching natively for you

**Comment by hanifbirgani** [comment] 2023-11-10 19:00
I have tested it, but it doesn't make any difference. Every time `htmx` sends a new request to the server the request doesn't get cached by the browser. I have used the `Cache-Control` header on the server response and even with the `hx-header` attribute on front-end.

**Comment by Telroshan** [comment] 2023-11-10 19:03
Hmm that sounds like a bug, I've been using it on some projects and it works just as any other regular requests.
Could you share the response info from your browser's dev tools' Network tab? To make sure the header's syntax is valid

**Comment by hanifbirgani** [comment] 2023-11-10 19:32
These are the response headers:

```text
HTTP/1.1 200 OK
Server: Werkzeug/3.0.0 Python/3.11.6
Date: Fri, 10 Nov 2023 19:30:21 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 17
Cache-Control: public, max-age=86400
Connection: close
```

**Comment by Telroshan** [comment] 2023-11-10 22:29
> These are the response headers:

Well, seems good to me, that's definitely weird 🤔
- Could you make sure you have not disabled caching in your browser's dev tools? (I'm asking because that happened to me once 😆 )
- Could you setup a repository with a minimal reproducible example to investigate that issue?

**Comment by alexpetros** [comment] 2023-11-11 02:43
I agree with @Telroshan. Not ruling out that there isn't some htmx issue at play, but the browser should cache network requests in accordance with the appropriate headers by default, even requests made via JS. It is possible to invalidate the cache in JS requests, but I don't think we're doing that.

**Comment by hanifbirgani** [comment] 2023-11-11 16:51
> Could you setup a repository with a minimal reproducible example to investigate that issue?

Sure, this is the git repo you can investigate the issue: https://github.com/hanifbirgani/htmx-cache-example

**Comment by Telroshan** [comment] 2023-11-11 17:13
Well, it works for me 😅 
_(I had to remove `htmx-cache.js` include as it was preventing requests from happening at all)_
With your initial code:
![image](https://github.com/bigskysoftware/htmx/assets/19146183/8673811f-7791-4c63-9260-b9fc604a5d00)
With a cache control set to `2` (so 2 seconds), I get the expected behavior where after 2 seconds the request is sent to the server again
![image](https://github.com/bigskysoftware/htmx/assets/19146183/58ea0f84-1748-43fd-a707-f8db49aacd9e)

**Comment by hanifbirgani** [comment] 2023-11-11 19:21
> Could you make sure you have not disabled caching in your browser's dev tools? (I'm asking because that happened to me once 😆 )

That was the point, the cache was disabled in the browser settings. I enabled the cache and it worked without the extension 👍

> Well, it works for me 😅
> (I had to remove htmx-cache.js include as it was preventing next requests from happening at all)

What if I prefer not to rely on the user's browser cache and instead utilize the htmx-extension cache? Is it possible to accomplish this objective with an htmx extension?

**Comment by Telroshan** [comment] 2023-11-12 06:21
You can definitely implement your own caching system, even though I really wouldn't recommend it in the situation described here (the 2 dropdowns) as the cache control header is a simple line of code to add to your backend that already solves the issue.
I'm not sure you can achieve everything you'd want from a caching system solely with a htmx extension i.e. without having to modify htmx' core, I can only encourage you to give it a shot though if you're interested.
Also please note that it seems very unlikely to me that we would merge such an extension in this repo.
You should also look into @nickchomey's suggestion about service workers.

Closing this issue as the described problem (no native cache for htmx) has been resolved (cache was turned off in the OP's browser)

**Closed by Telroshan** 2023-11-12 06:21 UTC

**Comment by hanifbirgani** [comment] 2023-11-12 20:24
You're right, I'll use the workers.

Please close the issue.
