### ISSUE TITLE
select element not displaying selected option in firefox

### ISSUE THREAD

**Issue by Anniepoo** [bigskysoftware/htmx#108] opened 2020-06-22 22:52 UTC
1. serve a web page containing the htmx file and the following

```
<select class="button" name="whosebot" hx-post="/htmx/whosebot">
<option value="You" name="You">You</option>
<option value="Train" name="Train">Train</option>
<option value="asdf" selected="true" name="asdf">asdf</option>
</select>
```

create a handler on server which replies with the same options, but the one chosen
is selected

load the page and change the selection a few times.

EXPECTED: displayed selection will be the one with selected="true"
OBSERVED:  on firefox 77.0.1on ubuntu 18.04, final value displayed will be randomly either the first item or the correct item
OBSERVED: on chrome Version 79.0.3945.130 (Official Build) (64-bit) on same machine always displays the correct item

Note that the DOM is correct, it's just not being displayed correctly:

https://twitter.com/AnnieTheObscure/status/1275155764152328193/photo/1

Using the browser debug, editing the select element to insert a trash attribute like foo="9" (which presumably causes the element to layout) causes the display to change to the correct selection.

Sometimes you can see it display something else briefly before displaying the final incorrect value.

here's the code fragment I was using. SWI-Prolog 8.0.3  (doubt this is server side related).

```
bot_selector -->
      html(
          [  \html_requires(htmx),
        div(class('bot-selector'), [
                select([class(button),
                        name(whosebot),
                        'hx-post'(location_by_id(whose_bot))],
                       \whose_bot_options),
                select([class(button),
                        name(whichbot),
                       'hx-post'(location_by_id(which_bot))],
                       \which_bot_options)
          ])]).

whose_bot_options -->
      { Users = ['You', 'Train' | Students],
        current_user(You),
        findall(Name, (user_property(Name, role(user)),
                       Name \= You,
                     user_property(Name, role(student(chatbots_that_dont_suck)))), Students),
        user_whose_bot(User)
        },
      bot_options(User, Users).

bot_options(_, []) --> [].
bot_options(Selected, [Selected |T]) -->
      html(option([value(Selected), selected(true), name(Selected)] , Selected)),
      bot_options(Selected, T).
bot_options(Selected, [Option |T]) -->
      { Selected \= Option },
      html(option([value(Option), name(Option)] , Option)),
      bot_options(Selected, T).

		 /*******************************
		 *          Server Side         *
		 *******************************/


:- http_handler(htmx(whosebot), whose_bot_handler, [id(whose_bot)]).

whose_bot_handler(Request) :-
        http_read_data(Request, Query, []),
        memberchk(whosebot=NewWho, Query),
        set_user_whose_bot(NewWho),
        format('Content-type: text/html~n~n'),
        phrase(whose_bot_options, Content),
        print_html(Content).


:- http_handler(htmx(whichbot), which_bot_handler, [id(which_bot)]).

which_bot_handler(Request) :-
        http_read_data(Request, Query, []),
        memberchk(whichbot=NewWho, Query),
        set_user_which_bot(NewWho),
        format('Content-type: text/html~n~n'),
        phrase(which_bot_options, Content),
        print_html(Content).
```

**Comment by chg20** [comment] 2020-06-23 00:24
I have reproduced this in FireFox in a test.  This looks like a deeply annoying FireFox bug that they don't consider a bug:

https://stackoverflow.com/questions/1479233/why-doesnt-firefox-show-the-correct-default-select-option

If you look at the HTML, it will be correct with the right option marked as select, but the select just sits there being wrong.  

Hmm.

**Comment by chg20** [comment] 2020-06-23 00:32
OK, on playing around with it, I declare this a firefox bug.  

Recommended work around is to switch to an outerHTML swap and nuke the entire select, which will behave correctly:

```html
<select class="button" name="whosebot" hx-post="/htmx/whosebot" hx-swap="outerHTML">
<option value="You" name="You">You</option>
<option value="Train" name="Train">Train</option>
<option value="asdf" selected="true" name="asdf">asdf</option>
</select>
```
And include the select tag in the HTML returned from  `/htmx/whosebot`

Surprising behaviour by FF.

**Closed by chg20** 2020-06-23 00:32 UTC

**Comment by wnortje** [comment] 2021-12-08 17:54
Including `autocomplete="off"` in the `<select>` fixes this for me.

See https://stackoverflow.com/a/10096033
