### ISSUE TITLE
Website layout

### ISSUE THREAD

**Issue by MattWilcox** [bigskysoftware/htmx#141] opened 2020-07-14 10:09 UTC
Unsure how to leave an issue about your own website as opposed to the project itself:

https://htmx.org/docs/#introduction  Has anyone tested the page between 720px wide and 1650px browser width? It's mostly unreadable due to horizontal overflow.

**Comment by 1cg** [comment] 2020-09-07 15:57
720px should be enough for anyone... :100: 

I tried using a really simple layout tool for the site, and this is what I get.  I'll try to fix it. 

If you know CSS and have a good idea on how to fix it with a minimum of complexity, I would love a pull request.

**Comment by MattWilcox** [comment] 2020-09-08 09:37
I'll see if I can, but tbh while I have a lot of experience on CSS... I don't use frameworks as they tend to get in my way more than help. All I noticed from a quick look was your columns are being implemented with `display: table-cell` and thats... certainly not current or best practice.

**Comment by bencroker** [comment] 2020-09-16 20:35
@MattWilcox Any help you can offer through a PR to the `dev` branch would be much appreciated!!
https://github.com/bigskysoftware/htmx/tree/dev/www

**Comment by Eroica** [comment] 2020-09-24 04:25
I see two separate issues.

1. On the homepage (`/`), there is a horizontal scrollbar even though there is no overflowing content.

This is caused by `.dark-hero` also having `.full-width`, and whose margin is calculated based on the `vw` unit.

The `vw` unit does not account for a vertical scrollbar though. The vertical scrollbar appears, naturally, because the content is too long (vertically) to fit on most displays.

Since you probably want to `.dark-hero` to fill the entire screen, I would forego relying on negative margins and `vw`, and simply put the container outside of `.c` (which restricts `.dark-hero`'s width originally). All site content is wrapped inside a `.c` currently to make it no longer than 55em and horizontally centered, so it's probably the easiest to put the banner from `index.md` into `layout.njk` conditionally:

https://github.com/Eroica/htmx/blob/3d506e5b56cf687068c5d4501c1b2c377c56c53a/www/_includes/layout.njk#L53

(Bonus: Gets rid of unsightly HTML inside `index.md` i.e. a Markdown file.)

2. Horizontal overflow on the `documentation` page caused by some `pre`s being too long.

This is a little bit more complicated. The root issue seems to be `overflow-x` behaving differently in blocks that are `display: table-cell`. I would replace table-based grids by a flex-based one (this still works on IE11). This can also get rid of some of the `1...10` boilerplate classes since you can simply tell a `.row` to fit the column size to its content.

To make a `pre` be horizontally scrollable (instead of displaying the scrollbar for the whole page), it must be wrapped inside a container that sets `overflow-x`. In this case, the only container is the `.10.col` itself.

I have roughly updated the layout parts to prevent a horizontal scrollbar here: https://github.com/Eroica/htmx/commit/c982b9487ffeb1a76c8f8db77fbf82ae1e00049b

There are some inline styles left for some quick fixes. If there is interest, I could split the commit more logically, and make a pull request. However, since this could potentially have bigger consequences (e.g. replacing table-based rows with flex-based ones), I wouldn't want to do this if the maintainers are uncomfortable with that.

I would also suggest removing the global vertical-align done by `* + * {...}`, and add that behavior to a separate class (in my case, `._vertical-spacing` only where it's necessary (e.g. text content). Otherwise you simply fight against this behavior if you want something to align horizontally, which navigation items and other _decorative_ elements are.

Other issues:

* The site layout is visually broken if the viewport size is 720px (more exact: When the viewport size is 45em).

This is because you actually need to differentiate `max-width` and `min-width` media queries by a single pixel (e.g. 719px and 720px). I suggest replacing em-based media queries with px-based ones; the few situations where em-based media queries might be a little bit more useful don't apply here.

**Comment by thewebartisan7** [comment] 2020-09-24 20:10
If you want I can make an update only of layout by using flexbox and keeping current style.
I would use simple html markup.

This is an example of layout:

```html
<!DOCTYPE html>
<html>
<head>
<style>
header nav {
    display: flex;
    justify-content: space-around;
}
main {
  display: flex;
  background-color: #fff;
  flex-direction: row
}
nav {
  background-color: #fff;
  margin: 10px;
  padding: 20px;
  font-size: 30px;
}
#content {
  background-color: #fff;
  margin: 10px;
  padding: 20px;
  font-size: 30px;
  flex-grow: 1
}
</style>
</head>
<body>
   <header>
      <nav>
                   <div hx-get="/" hx-target="body" hx-push-url="true" class="logo light">&lt;<a>/</a>&gt; htm<a>x</a></div>
                    <div>
                        <a href="/docs">docs</a>
                    </div>
                    <div>
                        <a href="/reference">reference</a>
                    </div>
                    <div>
                        <a href="/examples">examples</a>
                    </div>
                    <div>
                        <a href="/talk">talk</a>
                    </div>
                    <div>
                        <a href="https://github.com/sponsors/bigskysoftware?o=esb">sponsor</a>
                    </div>
                    <div>
                    </div>
                    <div>
                            <a href="https://github.com/bigskysoftware/htmx">github</a>
                            <iframe style="margin:auto;" src="https://ghbtns.com/github-btn.html?user=bigskysoftware&amp;repo=htmx&amp;type=star&amp;count=true" scrolling="0" title="Star htmx on GitHub" width="150" height="20" frameborder="0"></iframe>
                    </div>
                </nav>
     </header>

<main>
   <nav id="nav">
     <ul>
         <li><a href="#introduction">introduction</a></li>
         <li><a href="#installing">installing</a></li>
         <li><a href="#ajax">ajax</a>
      <ul>
  </nav>
  <div id="content">
      Content go here...
  </div>
</main>
</body>
</html>

```

Demo without style: https://jsfiddle.net/
Only this layout in action

**Comment by 1cg** [comment] 2020-09-27 22:08
I originally tool the layout from lit.css:

https://ajusa.github.io/lit/

And modified it.  I'm not wedded to it and I'm happy to take improvements.  I'd prefer to keep the CSS very simple for now, until I have time to convince @kerns to redo the whole website.

**Comment by Eroica** [comment] 2020-09-28 00:36
It's fine to rely on something simple like lit.css, but it does have that problem with the overflowing code.

Of course, if it doesn't bother you much, then we can just wait for the update.

**Comment by Maxim-Mazurok** [comment] 2020-11-28 13:02
Was trying to fix horizontal scroll, but I think that @Eroica suggested the best solution: move `hero` out of `content`. Horizontal scroll makes me sad :(

**Comment by constantinjoly** [comment] 2021-01-01 19:02
Adding to the `div class row` the property `table-layout: fixed` will make the content responsive and won't overflow anymore. Then maybe, you could make the `.c` a bit larger than 55em.
Even if I'm not a super experienced dev or webdesigner, I would very happy to participate and give some of my time for HTMX project if you were interested.

**Comment by 1cg** [comment] 2021-01-02 03:03
@constantinjoly I would be very happy if you lent some design expertise to the HTMX website!  It is very easy to get running on your local system:

```bash
$ npm install
$ cd www
$ ../node_modules/.bin/eleventy --serve
```
And then to to http://localhost:8080

All the web stuff is in the `/www` directory and as you edit it, it should live reload (eleventy is pretty slick)

Thank you!

**Comment by 1cg** [comment] 2021-01-11 02:21
This has been addressed to an extent, closing out for now

**Closed by 1cg** 2021-01-11 02:21 UTC
Labels: help wanted, website
