### ISSUE TITLE
chaining "load" and "every 5s" doesn't work as expected

### ISSUE THREAD

**Issue by faulander** [bigskysoftware/htmx#553] opened 2021-07-15 13:12 UTC
Code-Snippet:
`<div hx-get="/partial_zz/Technisch" hx-trigger="load, every 5s">`

Django GET-Output:
```15/Jul/2021 15:09:23] "GET /dashboard/ZZ/Technisch HTTP/1.1" 200 14193
[15/Jul/2021 15:09:23] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:24] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:25] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:25] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:26] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:27] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:28] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:28] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:29] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:29] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:30] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:31] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:32] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:32] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:33] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:33] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:35] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:35] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
[15/Jul/2021 15:09:36] "GET /partial_zz/Technisch HTTP/1.1" 200 5467
```

If i am using only "load" or only "every 5s" it works like a charm, but chaining doesn't.
Is there another way to "load once, then poll every 5s"?

**Comment by 1cg** [comment] 2021-07-15 21:44
Are you by any chance using `hx-swap="outerHTML"`?  I wonder if load is getting triggered multiple times...

**Comment by faulander** [comment] 2021-07-16 11:32
this is the whole template:
```
{% load dateandtime %}
<div hx-get="/partial_zz/Technisch" hx-trigger="every 5s">
<table class="table table-hover table-sm text-xsmall" style="font-size: 11px;">
  <thead>
    <tr>
      <th scope="col" style="width: 2%;">Nr</th>
      <th scope="col" style="width: 6%;">KURKAN</th>
      <th scope="col" style="width: 2%;">Prio</th>
      <th scope="col" style="width: 2%;">D</th>
      <th scope="col" style="width: 17%;">KAT</th>
      <th scope="col" style="width: 5%;">Status</th>
      <th scope="col" style="width: 31%;">Zusammenfassung</th>
      <th scope="col" style="width: 12%;">erstellt</th>
      <th scope="col" style="width: 19%;">Info</th>
      <th scope="col" style="width: 12%;">Termin</th>
    </tr>
  </thead>

{% for ticket in tickets %}
    <tr>
      <td><a href='https://www.helpdesk.advokat.at/jira/browse/{{ ticket.key }}'><i class="bi bi-link"></i></a></td>
      <td>{{ ticket.kurkan.0 }}</td>
      {% if ticket.priority == "Blocker" %}
        <td><i class="text-danger bi bi-exclamation-circle-fill"></i></td>
      {% elif ticket.priority == "High" %}
        <td><i class="text-warning bi bi-chevron-double-up"></i></td>
      {% elif ticket.priority == "Medium" %}
        <td><i class="text-success bi bi-chevron-up"></i></td>
      {% elif ticket.priority == "Low" %}
        <td><i class="text-primary bi bi-chevron-down"></i></td>
      {% elif ticket.priority == "Unwesentlich" %}
        <td><i class="text-primary bi bi-chevron-double-down"></i></td>
      {% else %}
        <td>{{ ticket.priority }}</td>
      {% endif %}
      <td>{{ ticket.dringlichkeit }}</td>
      <td>{{ ticket.component }}</td>
      {% if ticket.status == "Wartet auf den Support" %}
        <td>WAS</td>
      {%elif ticket.status == "Wird bearbeitet." %}
        <td>iA</td>
      {% else %}
        <td>{{ ticket.status }}</td>
      {% endif %}
      <td>{{ ticket.summary|truncatechars:44 }}</td>
      <td>{{ ticket.created|date_from_api:"d.m.y h:m" }}</td>
      <td>{{ ticket.info|default_if_none:"" }}</td>
      <td>{{ ticket.termin|date_from_api:"d.m.y h:m" }}</td>
    </tr>
  {% endfor %}
  </table>
</div>

```

**Comment by yanc0** [comment] 2021-09-06 06:11
Same here :hand: 

I would like to load content, then, poll every 10s. When chaining triggers like that: `load, every 10s`: the content is loaded after 10 seconds. This is not what I expected.

**Comment by 1cg** [comment] 2021-09-06 15:36
hmmm

this test is working locally for me in chrome and firefox:

```js
    var i = 1;
    this.server.respondWith("GET", "/test", function(xhr){
        xhr.respond(201, {}, "" + i++);
    });

    make('<div hx-get="/test" hx-trigger="load, every 5s">Init</div>');
```

It loads 1 immediately and then every 5 seconds loads a new number.  Looking at the code, this seems to be how the logic works: load and polling are handled separately and should init properly.

:expressionless:

**Comment by 1cg** [comment] 2021-11-02 22:37
update on this, I was unable to reproduce.  Are you still seeing this behavior?

**Comment by 1cg** [comment] 2022-05-13 15:11
closing as can't reproduce

**Closed by 1cg** 2022-05-13 15:11 UTC
