### ISSUE TITLE
`show` modifier not working  with outerHTML swap

### ISSUE THREAD

**Issue by jreviews** [bigskysoftware/htmx#307] opened 2021-01-04 20:44 UTC
Not sure if this is by design, but scrolling doesn't work with outerHTML. For example

`hx-swap="outerHTML show:top"`

**Comment by 1cg** [comment] 2021-02-05 18:52
Dupe of https://github.com/bigskysoftware/htmx/issues/335

Fixed in `dev` going out soon

**Closed by 1cg** 2021-02-05 18:52 UTC
