### ISSUE TITLE
How do we programmatically change htmx config?

### ISSUE THREAD

**Issue by jazoom** [bigskysoftware/htmx#2907] opened 2024-09-15 06:22 UTC
[This page](https://htmx.org/docs/#config) says to do this

```
htmx.config.allowEval = false;
```

But TypeScript is not allowing me to do that.

```
Cannot assign to 'allowEval' because it is a read-only property.ts(2540)
```

I know <meta> tags can be used but I want to keep the htmx setup in the same file and not have bits all over the place.

**Comment by Telroshan** [comment] 2024-09-15 07:36
Hey, I'm closing this as duplicate of #2850.
PR #2853 fixes it and will be in the next htmx release

**Closed by Telroshan** 2024-09-15 07:36 UTC

**Comment by jazoom** [comment] 2024-09-15 07:39
Sorry I did search. I guess I wasn't using the same terms as in that issue. Thank you.

**Comment by Telroshan** [comment] 2024-09-15 07:54
No worries!
